version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - 5432:5432
    user: root
    tty: true
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    #  - ./psql-data:/var/lib/postgresql/data

