/*
 * worker-monitor management API
 *
 * The API manages worker-monitor client data.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/MfsTeller/worker-monitor-server/api/go-server/go"
)

func main() {
	log.Printf("Server started")

	ClientDataApiService := openapi.NewClientDataApiService()
	ClientDataApiController := openapi.NewClientDataApiController(ClientDataApiService)

	router := openapi.NewRouter(ClientDataApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
