/*
 * worker-monitor management API
 *
 * The API manages worker-monitor client data.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClientDataApiService is a service that implents the logic for the ClientDataApiServicer
// This service should implement the business logic for every endpoint for the ClientDataApi API.
// Include any external packages or services that will be required by this service.
type ClientDataApiService struct {
}

// NewClientDataApiService creates a default api service
func NewClientDataApiService() ClientDataApiServicer {
	return &ClientDataApiService{}
}

// ClientdataClientIDGet - Get target client data by client ID
func (s *ClientDataApiService) ClientdataClientIDGet(clientID int64) (interface{}, error) {
	// TODO - update ClientdataClientIDGet with the required logic for this service method.
	// Add api_client_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	var clientData ClientData
	clientData.ClientId = clientID
	return clientData.PostgresRead(postgres), nil
	// return nil, errors.New("service method 'ClientdataClientIDGet' not implemented")
}

// ClientdataGet - Get target client data
func (s *ClientDataApiService) ClientdataGet() (interface{}, error) {
	// TODO - update ClientdataGet with the required logic for this service method.
	// Add api_client_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	clientData := ClientData{
		ClientId:         1,
		Name:             "Taro Sato",
		StartupDatetime:  "2020/04/30 10:00:00",
		ShutdownDatetime: "2020/04/30 20:00:00",
	}
	// return nil, errors.New("service method 'ClientdataGet' not implemented")
	return clientData, nil
}

// ClientdataPost - Register target client data
func (s *ClientDataApiService) ClientdataPost(clientData []ClientData) (interface{}, error) {
	// TODO - update ClientdataPost with the required logic for this service method.
	// Add api_client_data_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	for _, data := range clientData {
		data.PostgresCreate(postgres)
	}
	return nil, nil
	// return nil, errors.New("service method 'ClientdataPost' not implemented")
}
