/*
 * worker-monitor management API
 *
 * The API manages worker-monitor client data.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ClientData struct {

	ClientId int64 `json:"client_id"`

	Name string `json:"name,omitempty"`

	StartupDatetime string `json:"startup_datetime,omitempty"`

	ShutdownDatetime string `json:"shutdown_datetime,omitempty"`
}
